// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="convEncoder_Seq_convEncoder_Seq,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.018000,HLS_SYN_LAT=19,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=156,HLS_SYN_LUT=247,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module convEncoder_Seq (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_axis_TDATA,
        s_axis_TVALID,
        s_axis_TREADY,
        s_axis_TKEEP,
        s_axis_TSTRB,
        s_axis_TLAST,
        m_axis_TDATA,
        m_axis_TVALID,
        m_axis_TREADY,
        m_axis_TKEEP,
        m_axis_TSTRB,
        m_axis_TLAST
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] s_axis_TDATA;
input   s_axis_TVALID;
output   s_axis_TREADY;
input  [3:0] s_axis_TKEEP;
input  [3:0] s_axis_TSTRB;
input  [0:0] s_axis_TLAST;
output  [31:0] m_axis_TDATA;
output   m_axis_TVALID;
input   m_axis_TREADY;
output  [3:0] m_axis_TKEEP;
output  [3:0] m_axis_TSTRB;
output  [0:0] m_axis_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg s_axis_TREADY;
reg[31:0] m_axis_TDATA;
reg m_axis_TVALID;
reg[0:0] m_axis_TLAST;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [5:0] state;
reg    s_axis_TDATA_blk_n;
wire   [0:0] tmp_nbreadreq_fu_70_p6;
reg    m_axis_TDATA_blk_n;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [0:0] tmp_reg_174;
reg   [31:0] in_word_data_reg_178;
reg   [0:0] in_word_last_reg_183;
reg   [31:0] p_s_reg_191;
wire    grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start;
wire    grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_done;
wire    grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_idle;
wire    grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_ready;
wire   [5:0] grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_p_out;
wire    grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_p_out_ap_vld;
wire   [63:0] grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_encoded_out;
wire    grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_encoded_out_ap_vld;
reg    grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start_reg;
reg    ap_block_state1_ignore_call4;
wire    ap_CS_fsm_state2;
reg    ap_block_state4;
reg    ap_block_state1;
wire   [31:0] trunc_ln48_fu_140_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 state = 6'd0;
#0 grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start_reg = 1'b0;
end

convEncoder_Seq_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1 grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start),
    .ap_done(grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_done),
    .ap_idle(grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_idle),
    .ap_ready(grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_ready),
    .state_load(state),
    .in_word_data(in_word_data_reg_178),
    .p_out(grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_p_out),
    .p_out_ap_vld(grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_p_out_ap_vld),
    .encoded_out(grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_encoded_out),
    .encoded_out_ap_vld(grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_encoded_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call4) & (tmp_nbreadreq_fu_70_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start_reg <= 1'b1;
        end else if ((grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_ready == 1'b1)) begin
            grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        in_word_data_reg_178 <= s_axis_TDATA;
        in_word_last_reg_183 <= s_axis_TLAST;
        tmp_reg_174 <= tmp_nbreadreq_fu_70_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_s_reg_191 <= {{grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_encoded_out[63:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state4) & (tmp_reg_174 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        state <= grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_p_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axis_TREADY == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state4)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4) & (tmp_reg_174 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_TDATA = p_s_reg_191;
    end else if (((m_axis_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axis_TDATA = trunc_ln48_fu_140_p1;
    end else begin
        m_axis_TDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((tmp_reg_174 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        m_axis_TDATA_blk_n = m_axis_TREADY;
    end else begin
        m_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4) & (tmp_reg_174 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_TLAST = in_word_last_reg_183;
    end else if (((m_axis_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axis_TLAST = 1'd0;
    end else begin
        m_axis_TLAST = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state4) & (tmp_reg_174 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((m_axis_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        m_axis_TVALID = 1'b1;
    end else begin
        m_axis_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_70_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        s_axis_TDATA_blk_n = s_axis_TVALID;
    end else begin
        s_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (tmp_nbreadreq_fu_70_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        s_axis_TREADY = 1'b1;
    end else begin
        s_axis_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (tmp_nbreadreq_fu_70_p6 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((1'b0 == ap_block_state1) & (tmp_nbreadreq_fu_70_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((m_axis_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | ((tmp_nbreadreq_fu_70_p6 == 1'd1) & (s_axis_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state1_ignore_call4 = ((ap_start == 1'b0) | ((tmp_nbreadreq_fu_70_p6 == 1'd1) & (s_axis_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state4 = ((tmp_reg_174 == 1'd1) & (m_axis_TREADY == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start = grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start_reg;

assign m_axis_TKEEP = 4'd15;

assign m_axis_TSTRB = 4'd15;

assign tmp_nbreadreq_fu_70_p6 = s_axis_TVALID;

assign trunc_ln48_fu_140_p1 = grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_encoded_out[31:0];

endmodule //convEncoder_Seq
