set_property SRC_FILE_INFO {cfile:D:/vivado/throughput_zybo/throughput_zybo.srcs/constrs_1/new/constraints.xdc rfile:../../../throughput_zybo.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports ap_clk]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports ap_rst_n]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports measurement_done]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list ap_clk_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {state_q[0]} {state_q[1]}]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {cycs_q[0]} {cycs_q[1]} {cycs_q[2]} {cycs_q[3]} {cycs_q[4]} {cycs_q[5]} {cycs_q[6]} {cycs_q[7]} {cycs_q[8]} {cycs_q[9]} {cycs_q[10]} {cycs_q[11]} {cycs_q[12]} {cycs_q[13]} {cycs_q[14]} {cycs_q[15]} {cycs_q[16]} {cycs_q[17]} {cycs_q[18]} {cycs_q[19]} {cycs_q[20]} {cycs_q[21]} {cycs_q[22]} {cycs_q[23]} {cycs_q[24]} {cycs_q[25]} {cycs_q[26]} {cycs_q[27]} {cycs_q[28]} {cycs_q[29]} {cycs_q[30]} {cycs_q[31]} {cycs_q[32]} {cycs_q[33]} {cycs_q[34]} {cycs_q[35]} {cycs_q[36]} {cycs_q[37]} {cycs_q[38]} {cycs_q[39]} {cycs_q[40]} {cycs_q[41]} {cycs_q[42]} {cycs_q[43]} {cycs_q[44]} {cycs_q[45]} {cycs_q[46]} {cycs_q[47]} {cycs_q[48]} {cycs_q[49]} {cycs_q[50]} {cycs_q[51]} {cycs_q[52]} {cycs_q[53]} {cycs_q[54]} {cycs_q[55]} {cycs_q[56]} {cycs_q[57]} {cycs_q[58]} {cycs_q[59]} {cycs_q[60]} {cycs_q[61]} {cycs_q[62]} {cycs_q[63]}]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {bits_q[0]} {bits_q[1]} {bits_q[2]} {bits_q[3]} {bits_q[4]} {bits_q[5]} {bits_q[6]} {bits_q[7]} {bits_q[8]} {bits_q[9]} {bits_q[10]} {bits_q[11]} {bits_q[12]} {bits_q[13]} {bits_q[14]} {bits_q[15]} {bits_q[16]} {bits_q[17]} {bits_q[18]} {bits_q[19]} {bits_q[20]} {bits_q[21]} {bits_q[22]} {bits_q[23]} {bits_q[24]} {bits_q[25]} {bits_q[26]} {bits_q[27]} {bits_q[28]} {bits_q[29]} {bits_q[30]} {bits_q[31]} {bits_q[32]} {bits_q[33]} {bits_q[34]} {bits_q[35]} {bits_q[36]} {bits_q[37]} {bits_q[38]} {bits_q[39]} {bits_q[40]} {bits_q[41]} {bits_q[42]} {bits_q[43]} {bits_q[44]} {bits_q[45]} {bits_q[46]} {bits_q[47]} {bits_q[48]} {bits_q[49]} {bits_q[50]} {bits_q[51]} {bits_q[52]} {bits_q[53]} {bits_q[54]} {bits_q[55]} {bits_q[56]} {bits_q[57]} {bits_q[58]} {bits_q[59]} {bits_q[60]} {bits_q[61]} {bits_q[62]} {bits_q[63]}]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list measurement_done_OBUF]]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 125000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets ap_clk_IBUF_BUFG]
