// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module convEncoder_Seq_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_load,
        in_word_data,
        p_out,
        p_out_ap_vld,
        encoded_out,
        encoded_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [5:0] state_load;
input  [31:0] in_word_data;
output  [5:0] p_out;
output   p_out_ap_vld;
output  [63:0] encoded_out;
output   encoded_out_ap_vld;

reg ap_idle;
reg p_out_ap_vld;
reg encoded_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln40_fu_114_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [63:0] encoded_fu_58;
wire   [63:0] encoded_1_fu_247_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [5:0] i_fu_62;
wire   [5:0] i_2_fu_120_p2;
reg   [5:0] empty_fu_66;
wire   [5:0] or_ln_fu_225_p3;
wire    ap_block_pp0_stage0_01001;
wire   [4:0] bit_fu_136_p2;
wire   [0:0] bit_fu_136_p3;
wire   [0:0] tmp_2_fu_163_p3;
wire   [0:0] trunc_ln10_fu_143_p1;
wire   [0:0] tmp_fu_147_p3;
wire   [0:0] tmp_1_fu_155_p3;
wire   [0:0] xor_ln10_fu_171_p2;
wire   [0:0] xor_ln10_2_fu_183_p2;
wire   [0:0] xor_ln10_1_fu_177_p2;
wire   [0:0] tmp_3_fu_195_p3;
wire   [0:0] xor_ln11_1_fu_209_p2;
wire   [0:0] xor_ln11_fu_203_p2;
wire   [4:0] trunc_ln13_fu_221_p1;
wire   [0:0] g2_fu_215_p2;
wire   [0:0] g1_fu_189_p2;
wire   [1:0] encoded_1_fu_247_p2;
wire   [5:0] encoded_1_fu_247_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [0:0] bit_fu_136_p0;
wire   [63:0] encoded_1_fu_247_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 encoded_fu_58 = 64'd0;
#0 i_fu_62 = 6'd0;
#0 empty_fu_66 = 6'd0;
#0 ap_done_reg = 1'b0;
end

convEncoder_Seq_bitselect_1ns_32ns_5ns_1_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 5 ))
bitselect_1ns_32ns_5ns_1_1_1_U1(
    .din(in_word_data),
    .sel(bit_fu_136_p2),
    .dout(bit_fu_136_p3)
);

convEncoder_Seq_partset_64ns_64ns_2ns_6ns_64_1_1 #(
    .DATAWIDTH( 64 ),
    .DATA1WIDTH( 2 ),
    .ADDRWIDTH( 6 ))
partset_64ns_64ns_2ns_6ns_64_1_1_U2(
    .din(encoded_fu_58),
    .value(encoded_1_fu_247_p2),
    .sel(encoded_1_fu_247_p3),
    .dout(encoded_1_fu_247_p4)
);

convEncoder_Seq_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_fu_66 <= state_load;
        end else if (((icmp_ln40_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_fu_66 <= or_ln_fu_225_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            encoded_fu_58 <= 64'd0;
        end else if (((icmp_ln40_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            encoded_fu_58 <= encoded_1_fu_247_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_62 <= 6'd0;
        end else if (((icmp_ln40_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_62 <= i_2_fu_120_p2;
        end
    end
end

always @ (*) begin
    if (((icmp_ln40_fu_114_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln40_fu_114_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        encoded_out_ap_vld = 1'b1;
    end else begin
        encoded_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln40_fu_114_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign bit_fu_136_p2 = i_fu_62[4:0];

assign encoded_1_fu_247_p2 = {{g2_fu_215_p2}, {g1_fu_189_p2}};

assign encoded_1_fu_247_p3 = i_fu_62 << 6'd1;

assign encoded_out = encoded_fu_58;

assign g1_fu_189_p2 = (xor_ln10_2_fu_183_p2 ^ xor_ln10_1_fu_177_p2);

assign g2_fu_215_p2 = (xor_ln11_fu_203_p2 ^ xor_ln11_1_fu_209_p2);

assign i_2_fu_120_p2 = (i_fu_62 + 6'd1);

assign icmp_ln40_fu_114_p2 = ((i_fu_62 == 6'd32) ? 1'b1 : 1'b0);

assign or_ln_fu_225_p3 = {{trunc_ln13_fu_221_p1}, {bit_fu_136_p3}};

assign p_out = empty_fu_66;

assign tmp_1_fu_155_p3 = empty_fu_66[32'd2];

assign tmp_2_fu_163_p3 = empty_fu_66[32'd5];

assign tmp_3_fu_195_p3 = empty_fu_66[32'd4];

assign tmp_fu_147_p3 = empty_fu_66[32'd1];

assign trunc_ln10_fu_143_p1 = empty_fu_66[0:0];

assign trunc_ln13_fu_221_p1 = empty_fu_66[4:0];

assign xor_ln10_1_fu_177_p2 = (trunc_ln10_fu_143_p1 ^ tmp_fu_147_p3);

assign xor_ln10_2_fu_183_p2 = (xor_ln10_fu_171_p2 ^ tmp_1_fu_155_p3);

assign xor_ln10_fu_171_p2 = (tmp_2_fu_163_p3 ^ bit_fu_136_p3);

assign xor_ln11_1_fu_209_p2 = (xor_ln10_fu_171_p2 ^ tmp_3_fu_195_p3);

assign xor_ln11_fu_203_p2 = (tmp_fu_147_p3 ^ tmp_1_fu_155_p3);

endmodule //convEncoder_Seq_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1
