// ==============================================================
// Generated by Vitis HLS v
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module viterbi_decoder_viterbi_decoder_Pipeline_TRACEBACK (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        best_state_32,
        survivor_address0,
        survivor_ce0,
        survivor_q0,
        survivor_1_address0,
        survivor_1_ce0,
        survivor_1_q0,
        survivor_2_address0,
        survivor_2_ce0,
        survivor_2_q0,
        survivor_3_address0,
        survivor_3_ce0,
        survivor_3_q0,
        survivor_4_address0,
        survivor_4_ce0,
        survivor_4_q0,
        survivor_5_address0,
        survivor_5_ce0,
        survivor_5_q0,
        survivor_6_address0,
        survivor_6_ce0,
        survivor_6_q0,
        survivor_7_address0,
        survivor_7_ce0,
        survivor_7_q0,
        survivor_8_address0,
        survivor_8_ce0,
        survivor_8_q0,
        survivor_9_address0,
        survivor_9_ce0,
        survivor_9_q0,
        survivor_10_address0,
        survivor_10_ce0,
        survivor_10_q0,
        survivor_11_address0,
        survivor_11_ce0,
        survivor_11_q0,
        survivor_12_address0,
        survivor_12_ce0,
        survivor_12_q0,
        survivor_13_address0,
        survivor_13_ce0,
        survivor_13_q0,
        survivor_14_address0,
        survivor_14_ce0,
        survivor_14_q0,
        survivor_15_address0,
        survivor_15_ce0,
        survivor_15_q0,
        survivor_16_address0,
        survivor_16_ce0,
        survivor_16_q0,
        survivor_17_address0,
        survivor_17_ce0,
        survivor_17_q0,
        survivor_18_address0,
        survivor_18_ce0,
        survivor_18_q0,
        survivor_19_address0,
        survivor_19_ce0,
        survivor_19_q0,
        survivor_20_address0,
        survivor_20_ce0,
        survivor_20_q0,
        survivor_21_address0,
        survivor_21_ce0,
        survivor_21_q0,
        survivor_22_address0,
        survivor_22_ce0,
        survivor_22_q0,
        survivor_23_address0,
        survivor_23_ce0,
        survivor_23_q0,
        survivor_24_address0,
        survivor_24_ce0,
        survivor_24_q0,
        survivor_25_address0,
        survivor_25_ce0,
        survivor_25_q0,
        survivor_26_address0,
        survivor_26_ce0,
        survivor_26_q0,
        survivor_27_address0,
        survivor_27_ce0,
        survivor_27_q0,
        survivor_28_address0,
        survivor_28_ce0,
        survivor_28_q0,
        survivor_29_address0,
        survivor_29_ce0,
        survivor_29_q0,
        survivor_30_address0,
        survivor_30_ce0,
        survivor_30_q0,
        survivor_31_address0,
        survivor_31_ce0,
        survivor_31_q0,
        survivor_32_address0,
        survivor_32_ce0,
        survivor_32_q0,
        survivor_33_address0,
        survivor_33_ce0,
        survivor_33_q0,
        survivor_34_address0,
        survivor_34_ce0,
        survivor_34_q0,
        survivor_35_address0,
        survivor_35_ce0,
        survivor_35_q0,
        survivor_36_address0,
        survivor_36_ce0,
        survivor_36_q0,
        survivor_37_address0,
        survivor_37_ce0,
        survivor_37_q0,
        survivor_38_address0,
        survivor_38_ce0,
        survivor_38_q0,
        survivor_39_address0,
        survivor_39_ce0,
        survivor_39_q0,
        survivor_40_address0,
        survivor_40_ce0,
        survivor_40_q0,
        survivor_41_address0,
        survivor_41_ce0,
        survivor_41_q0,
        survivor_42_address0,
        survivor_42_ce0,
        survivor_42_q0,
        survivor_43_address0,
        survivor_43_ce0,
        survivor_43_q0,
        survivor_44_address0,
        survivor_44_ce0,
        survivor_44_q0,
        survivor_45_address0,
        survivor_45_ce0,
        survivor_45_q0,
        survivor_46_address0,
        survivor_46_ce0,
        survivor_46_q0,
        survivor_47_address0,
        survivor_47_ce0,
        survivor_47_q0,
        survivor_48_address0,
        survivor_48_ce0,
        survivor_48_q0,
        survivor_49_address0,
        survivor_49_ce0,
        survivor_49_q0,
        survivor_50_address0,
        survivor_50_ce0,
        survivor_50_q0,
        survivor_51_address0,
        survivor_51_ce0,
        survivor_51_q0,
        survivor_52_address0,
        survivor_52_ce0,
        survivor_52_q0,
        survivor_53_address0,
        survivor_53_ce0,
        survivor_53_q0,
        survivor_54_address0,
        survivor_54_ce0,
        survivor_54_q0,
        survivor_55_address0,
        survivor_55_ce0,
        survivor_55_q0,
        survivor_56_address0,
        survivor_56_ce0,
        survivor_56_q0,
        survivor_57_address0,
        survivor_57_ce0,
        survivor_57_q0,
        survivor_58_address0,
        survivor_58_ce0,
        survivor_58_q0,
        survivor_59_address0,
        survivor_59_ce0,
        survivor_59_q0,
        survivor_60_address0,
        survivor_60_ce0,
        survivor_60_q0,
        survivor_61_address0,
        survivor_61_ce0,
        survivor_61_q0,
        survivor_62_address0,
        survivor_62_ce0,
        survivor_62_q0,
        survivor_63_address0,
        survivor_63_ce0,
        survivor_63_q0,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld,
        p_out4,
        p_out4_ap_vld,
        p_out5,
        p_out5_ap_vld,
        p_out6,
        p_out6_ap_vld,
        p_out7,
        p_out7_ap_vld,
        p_out8,
        p_out8_ap_vld,
        p_out9,
        p_out9_ap_vld,
        p_out10,
        p_out10_ap_vld,
        p_out11,
        p_out11_ap_vld,
        p_out12,
        p_out12_ap_vld,
        p_out13,
        p_out13_ap_vld,
        p_out14,
        p_out14_ap_vld,
        p_out15,
        p_out15_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [5:0] best_state_32;
output  [4:0] survivor_address0;
output   survivor_ce0;
input  [0:0] survivor_q0;
output  [4:0] survivor_1_address0;
output   survivor_1_ce0;
input  [0:0] survivor_1_q0;
output  [4:0] survivor_2_address0;
output   survivor_2_ce0;
input  [0:0] survivor_2_q0;
output  [4:0] survivor_3_address0;
output   survivor_3_ce0;
input  [0:0] survivor_3_q0;
output  [4:0] survivor_4_address0;
output   survivor_4_ce0;
input  [0:0] survivor_4_q0;
output  [4:0] survivor_5_address0;
output   survivor_5_ce0;
input  [0:0] survivor_5_q0;
output  [4:0] survivor_6_address0;
output   survivor_6_ce0;
input  [0:0] survivor_6_q0;
output  [4:0] survivor_7_address0;
output   survivor_7_ce0;
input  [0:0] survivor_7_q0;
output  [4:0] survivor_8_address0;
output   survivor_8_ce0;
input  [0:0] survivor_8_q0;
output  [4:0] survivor_9_address0;
output   survivor_9_ce0;
input  [0:0] survivor_9_q0;
output  [4:0] survivor_10_address0;
output   survivor_10_ce0;
input  [0:0] survivor_10_q0;
output  [4:0] survivor_11_address0;
output   survivor_11_ce0;
input  [0:0] survivor_11_q0;
output  [4:0] survivor_12_address0;
output   survivor_12_ce0;
input  [0:0] survivor_12_q0;
output  [4:0] survivor_13_address0;
output   survivor_13_ce0;
input  [0:0] survivor_13_q0;
output  [4:0] survivor_14_address0;
output   survivor_14_ce0;
input  [0:0] survivor_14_q0;
output  [4:0] survivor_15_address0;
output   survivor_15_ce0;
input  [0:0] survivor_15_q0;
output  [4:0] survivor_16_address0;
output   survivor_16_ce0;
input  [0:0] survivor_16_q0;
output  [4:0] survivor_17_address0;
output   survivor_17_ce0;
input  [0:0] survivor_17_q0;
output  [4:0] survivor_18_address0;
output   survivor_18_ce0;
input  [0:0] survivor_18_q0;
output  [4:0] survivor_19_address0;
output   survivor_19_ce0;
input  [0:0] survivor_19_q0;
output  [4:0] survivor_20_address0;
output   survivor_20_ce0;
input  [0:0] survivor_20_q0;
output  [4:0] survivor_21_address0;
output   survivor_21_ce0;
input  [0:0] survivor_21_q0;
output  [4:0] survivor_22_address0;
output   survivor_22_ce0;
input  [0:0] survivor_22_q0;
output  [4:0] survivor_23_address0;
output   survivor_23_ce0;
input  [0:0] survivor_23_q0;
output  [4:0] survivor_24_address0;
output   survivor_24_ce0;
input  [0:0] survivor_24_q0;
output  [4:0] survivor_25_address0;
output   survivor_25_ce0;
input  [0:0] survivor_25_q0;
output  [4:0] survivor_26_address0;
output   survivor_26_ce0;
input  [0:0] survivor_26_q0;
output  [4:0] survivor_27_address0;
output   survivor_27_ce0;
input  [0:0] survivor_27_q0;
output  [4:0] survivor_28_address0;
output   survivor_28_ce0;
input  [0:0] survivor_28_q0;
output  [4:0] survivor_29_address0;
output   survivor_29_ce0;
input  [0:0] survivor_29_q0;
output  [4:0] survivor_30_address0;
output   survivor_30_ce0;
input  [0:0] survivor_30_q0;
output  [4:0] survivor_31_address0;
output   survivor_31_ce0;
input  [0:0] survivor_31_q0;
output  [4:0] survivor_32_address0;
output   survivor_32_ce0;
input  [0:0] survivor_32_q0;
output  [4:0] survivor_33_address0;
output   survivor_33_ce0;
input  [0:0] survivor_33_q0;
output  [4:0] survivor_34_address0;
output   survivor_34_ce0;
input  [0:0] survivor_34_q0;
output  [4:0] survivor_35_address0;
output   survivor_35_ce0;
input  [0:0] survivor_35_q0;
output  [4:0] survivor_36_address0;
output   survivor_36_ce0;
input  [0:0] survivor_36_q0;
output  [4:0] survivor_37_address0;
output   survivor_37_ce0;
input  [0:0] survivor_37_q0;
output  [4:0] survivor_38_address0;
output   survivor_38_ce0;
input  [0:0] survivor_38_q0;
output  [4:0] survivor_39_address0;
output   survivor_39_ce0;
input  [0:0] survivor_39_q0;
output  [4:0] survivor_40_address0;
output   survivor_40_ce0;
input  [0:0] survivor_40_q0;
output  [4:0] survivor_41_address0;
output   survivor_41_ce0;
input  [0:0] survivor_41_q0;
output  [4:0] survivor_42_address0;
output   survivor_42_ce0;
input  [0:0] survivor_42_q0;
output  [4:0] survivor_43_address0;
output   survivor_43_ce0;
input  [0:0] survivor_43_q0;
output  [4:0] survivor_44_address0;
output   survivor_44_ce0;
input  [0:0] survivor_44_q0;
output  [4:0] survivor_45_address0;
output   survivor_45_ce0;
input  [0:0] survivor_45_q0;
output  [4:0] survivor_46_address0;
output   survivor_46_ce0;
input  [0:0] survivor_46_q0;
output  [4:0] survivor_47_address0;
output   survivor_47_ce0;
input  [0:0] survivor_47_q0;
output  [4:0] survivor_48_address0;
output   survivor_48_ce0;
input  [0:0] survivor_48_q0;
output  [4:0] survivor_49_address0;
output   survivor_49_ce0;
input  [0:0] survivor_49_q0;
output  [4:0] survivor_50_address0;
output   survivor_50_ce0;
input  [0:0] survivor_50_q0;
output  [4:0] survivor_51_address0;
output   survivor_51_ce0;
input  [0:0] survivor_51_q0;
output  [4:0] survivor_52_address0;
output   survivor_52_ce0;
input  [0:0] survivor_52_q0;
output  [4:0] survivor_53_address0;
output   survivor_53_ce0;
input  [0:0] survivor_53_q0;
output  [4:0] survivor_54_address0;
output   survivor_54_ce0;
input  [0:0] survivor_54_q0;
output  [4:0] survivor_55_address0;
output   survivor_55_ce0;
input  [0:0] survivor_55_q0;
output  [4:0] survivor_56_address0;
output   survivor_56_ce0;
input  [0:0] survivor_56_q0;
output  [4:0] survivor_57_address0;
output   survivor_57_ce0;
input  [0:0] survivor_57_q0;
output  [4:0] survivor_58_address0;
output   survivor_58_ce0;
input  [0:0] survivor_58_q0;
output  [4:0] survivor_59_address0;
output   survivor_59_ce0;
input  [0:0] survivor_59_q0;
output  [4:0] survivor_60_address0;
output   survivor_60_ce0;
input  [0:0] survivor_60_q0;
output  [4:0] survivor_61_address0;
output   survivor_61_ce0;
input  [0:0] survivor_61_q0;
output  [4:0] survivor_62_address0;
output   survivor_62_ce0;
input  [0:0] survivor_62_q0;
output  [4:0] survivor_63_address0;
output   survivor_63_ce0;
input  [0:0] survivor_63_q0;
output  [0:0] p_out;
output   p_out_ap_vld;
output  [0:0] p_out1;
output   p_out1_ap_vld;
output  [0:0] p_out2;
output   p_out2_ap_vld;
output  [0:0] p_out3;
output   p_out3_ap_vld;
output  [0:0] p_out4;
output   p_out4_ap_vld;
output  [0:0] p_out5;
output   p_out5_ap_vld;
output  [0:0] p_out6;
output   p_out6_ap_vld;
output  [0:0] p_out7;
output   p_out7_ap_vld;
output  [0:0] p_out8;
output   p_out8_ap_vld;
output  [0:0] p_out9;
output   p_out9_ap_vld;
output  [0:0] p_out10;
output   p_out10_ap_vld;
output  [0:0] p_out11;
output   p_out11_ap_vld;
output  [0:0] p_out12;
output   p_out12_ap_vld;
output  [0:0] p_out13;
output   p_out13_ap_vld;
output  [0:0] p_out14;
output   p_out14_ap_vld;
output  [0:0] p_out15;
output   p_out15_ap_vld;

reg ap_idle;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;
reg p_out4_ap_vld;
reg p_out5_ap_vld;
reg p_out6_ap_vld;
reg p_out7_ap_vld;
reg p_out8_ap_vld;
reg p_out9_ap_vld;
reg p_out10_ap_vld;
reg p_out11_ap_vld;
reg p_out12_ap_vld;
reg p_out13_ap_vld;
reg p_out14_ap_vld;
reg p_out15_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_1397_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] trunc_ln302_fu_1473_p1;
reg   [3:0] trunc_ln302_reg_2075;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln302_fu_1405_p1;
wire    ap_block_pp0_stage0;
reg   [5:0] cur_state_fu_362;
wire   [5:0] cur_state_1_fu_1884_p3;
wire    ap_loop_init;
reg   [4:0] t_1_fu_366;
wire   [4:0] add_ln302_fu_1511_p2;
reg   [4:0] ap_sig_allocacmp_t;
reg   [0:0] empty_fu_370;
reg   [0:0] empty_11_fu_374;
reg   [0:0] empty_12_fu_378;
reg   [0:0] empty_13_fu_382;
reg   [0:0] empty_14_fu_386;
reg   [0:0] empty_15_fu_390;
reg   [0:0] empty_16_fu_394;
reg   [0:0] empty_17_fu_398;
reg   [0:0] empty_18_fu_402;
reg   [0:0] empty_19_fu_406;
reg   [0:0] empty_20_fu_410;
reg   [0:0] empty_21_fu_414;
reg   [0:0] empty_22_fu_418;
reg   [0:0] empty_23_fu_422;
reg   [0:0] empty_24_fu_426;
reg   [0:0] empty_25_fu_430;
wire    ap_block_pp0_stage0_01001;
reg    survivor_ce0_local;
reg    survivor_1_ce0_local;
reg    survivor_2_ce0_local;
reg    survivor_3_ce0_local;
reg    survivor_4_ce0_local;
reg    survivor_5_ce0_local;
reg    survivor_6_ce0_local;
reg    survivor_7_ce0_local;
reg    survivor_8_ce0_local;
reg    survivor_9_ce0_local;
reg    survivor_10_ce0_local;
reg    survivor_11_ce0_local;
reg    survivor_12_ce0_local;
reg    survivor_13_ce0_local;
reg    survivor_14_ce0_local;
reg    survivor_15_ce0_local;
reg    survivor_16_ce0_local;
reg    survivor_17_ce0_local;
reg    survivor_18_ce0_local;
reg    survivor_19_ce0_local;
reg    survivor_20_ce0_local;
reg    survivor_21_ce0_local;
reg    survivor_22_ce0_local;
reg    survivor_23_ce0_local;
reg    survivor_24_ce0_local;
reg    survivor_25_ce0_local;
reg    survivor_26_ce0_local;
reg    survivor_27_ce0_local;
reg    survivor_28_ce0_local;
reg    survivor_29_ce0_local;
reg    survivor_30_ce0_local;
reg    survivor_31_ce0_local;
reg    survivor_32_ce0_local;
reg    survivor_33_ce0_local;
reg    survivor_34_ce0_local;
reg    survivor_35_ce0_local;
reg    survivor_36_ce0_local;
reg    survivor_37_ce0_local;
reg    survivor_38_ce0_local;
reg    survivor_39_ce0_local;
reg    survivor_40_ce0_local;
reg    survivor_41_ce0_local;
reg    survivor_42_ce0_local;
reg    survivor_43_ce0_local;
reg    survivor_44_ce0_local;
reg    survivor_45_ce0_local;
reg    survivor_46_ce0_local;
reg    survivor_47_ce0_local;
reg    survivor_48_ce0_local;
reg    survivor_49_ce0_local;
reg    survivor_50_ce0_local;
reg    survivor_51_ce0_local;
reg    survivor_52_ce0_local;
reg    survivor_53_ce0_local;
reg    survivor_54_ce0_local;
reg    survivor_55_ce0_local;
reg    survivor_56_ce0_local;
reg    survivor_57_ce0_local;
reg    survivor_58_ce0_local;
reg    survivor_59_ce0_local;
reg    survivor_60_ce0_local;
reg    survivor_61_ce0_local;
reg    survivor_62_ce0_local;
reg    survivor_63_ce0_local;
wire   [0:0] surv_fu_1616_p129;
wire   [4:0] cur_lo5_fu_1880_p1;
wire   [0:0] surv_fu_1616_p131;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [5:0] surv_fu_1616_p1;
wire   [5:0] surv_fu_1616_p3;
wire   [5:0] surv_fu_1616_p5;
wire   [5:0] surv_fu_1616_p7;
wire   [5:0] surv_fu_1616_p9;
wire   [5:0] surv_fu_1616_p11;
wire   [5:0] surv_fu_1616_p13;
wire   [5:0] surv_fu_1616_p15;
wire   [5:0] surv_fu_1616_p17;
wire   [5:0] surv_fu_1616_p19;
wire   [5:0] surv_fu_1616_p21;
wire   [5:0] surv_fu_1616_p23;
wire   [5:0] surv_fu_1616_p25;
wire   [5:0] surv_fu_1616_p27;
wire   [5:0] surv_fu_1616_p29;
wire   [5:0] surv_fu_1616_p31;
wire   [5:0] surv_fu_1616_p33;
wire   [5:0] surv_fu_1616_p35;
wire   [5:0] surv_fu_1616_p37;
wire   [5:0] surv_fu_1616_p39;
wire   [5:0] surv_fu_1616_p41;
wire   [5:0] surv_fu_1616_p43;
wire   [5:0] surv_fu_1616_p45;
wire   [5:0] surv_fu_1616_p47;
wire   [5:0] surv_fu_1616_p49;
wire   [5:0] surv_fu_1616_p51;
wire   [5:0] surv_fu_1616_p53;
wire   [5:0] surv_fu_1616_p55;
wire   [5:0] surv_fu_1616_p57;
wire   [5:0] surv_fu_1616_p59;
wire   [5:0] surv_fu_1616_p61;
wire   [5:0] surv_fu_1616_p63;
wire  signed [5:0] surv_fu_1616_p65;
wire  signed [5:0] surv_fu_1616_p67;
wire  signed [5:0] surv_fu_1616_p69;
wire  signed [5:0] surv_fu_1616_p71;
wire  signed [5:0] surv_fu_1616_p73;
wire  signed [5:0] surv_fu_1616_p75;
wire  signed [5:0] surv_fu_1616_p77;
wire  signed [5:0] surv_fu_1616_p79;
wire  signed [5:0] surv_fu_1616_p81;
wire  signed [5:0] surv_fu_1616_p83;
wire  signed [5:0] surv_fu_1616_p85;
wire  signed [5:0] surv_fu_1616_p87;
wire  signed [5:0] surv_fu_1616_p89;
wire  signed [5:0] surv_fu_1616_p91;
wire  signed [5:0] surv_fu_1616_p93;
wire  signed [5:0] surv_fu_1616_p95;
wire  signed [5:0] surv_fu_1616_p97;
wire  signed [5:0] surv_fu_1616_p99;
wire  signed [5:0] surv_fu_1616_p101;
wire  signed [5:0] surv_fu_1616_p103;
wire  signed [5:0] surv_fu_1616_p105;
wire  signed [5:0] surv_fu_1616_p107;
wire  signed [5:0] surv_fu_1616_p109;
wire  signed [5:0] surv_fu_1616_p111;
wire  signed [5:0] surv_fu_1616_p113;
wire  signed [5:0] surv_fu_1616_p115;
wire  signed [5:0] surv_fu_1616_p117;
wire  signed [5:0] surv_fu_1616_p119;
wire  signed [5:0] surv_fu_1616_p121;
wire  signed [5:0] surv_fu_1616_p123;
wire  signed [5:0] surv_fu_1616_p125;
wire  signed [5:0] surv_fu_1616_p127;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 cur_state_fu_362 = 6'd0;
#0 t_1_fu_366 = 5'd0;
#0 empty_fu_370 = 1'd0;
#0 empty_11_fu_374 = 1'd0;
#0 empty_12_fu_378 = 1'd0;
#0 empty_13_fu_382 = 1'd0;
#0 empty_14_fu_386 = 1'd0;
#0 empty_15_fu_390 = 1'd0;
#0 empty_16_fu_394 = 1'd0;
#0 empty_17_fu_398 = 1'd0;
#0 empty_18_fu_402 = 1'd0;
#0 empty_19_fu_406 = 1'd0;
#0 empty_20_fu_410 = 1'd0;
#0 empty_21_fu_414 = 1'd0;
#0 empty_22_fu_418 = 1'd0;
#0 empty_23_fu_422 = 1'd0;
#0 empty_24_fu_426 = 1'd0;
#0 empty_25_fu_430 = 1'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) viterbi_decoder_sparsemux_129_6_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 6'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 6'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 6'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 6'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 6'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 6'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 6'h7 ),
    .din7_WIDTH( 1 ),
    .CASE8( 6'h8 ),
    .din8_WIDTH( 1 ),
    .CASE9( 6'h9 ),
    .din9_WIDTH( 1 ),
    .CASE10( 6'hA ),
    .din10_WIDTH( 1 ),
    .CASE11( 6'hB ),
    .din11_WIDTH( 1 ),
    .CASE12( 6'hC ),
    .din12_WIDTH( 1 ),
    .CASE13( 6'hD ),
    .din13_WIDTH( 1 ),
    .CASE14( 6'hE ),
    .din14_WIDTH( 1 ),
    .CASE15( 6'hF ),
    .din15_WIDTH( 1 ),
    .CASE16( 6'h10 ),
    .din16_WIDTH( 1 ),
    .CASE17( 6'h11 ),
    .din17_WIDTH( 1 ),
    .CASE18( 6'h12 ),
    .din18_WIDTH( 1 ),
    .CASE19( 6'h13 ),
    .din19_WIDTH( 1 ),
    .CASE20( 6'h14 ),
    .din20_WIDTH( 1 ),
    .CASE21( 6'h15 ),
    .din21_WIDTH( 1 ),
    .CASE22( 6'h16 ),
    .din22_WIDTH( 1 ),
    .CASE23( 6'h17 ),
    .din23_WIDTH( 1 ),
    .CASE24( 6'h18 ),
    .din24_WIDTH( 1 ),
    .CASE25( 6'h19 ),
    .din25_WIDTH( 1 ),
    .CASE26( 6'h1A ),
    .din26_WIDTH( 1 ),
    .CASE27( 6'h1B ),
    .din27_WIDTH( 1 ),
    .CASE28( 6'h1C ),
    .din28_WIDTH( 1 ),
    .CASE29( 6'h1D ),
    .din29_WIDTH( 1 ),
    .CASE30( 6'h1E ),
    .din30_WIDTH( 1 ),
    .CASE31( 6'h1F ),
    .din31_WIDTH( 1 ),
    .CASE32( 6'h20 ),
    .din32_WIDTH( 1 ),
    .CASE33( 6'h21 ),
    .din33_WIDTH( 1 ),
    .CASE34( 6'h22 ),
    .din34_WIDTH( 1 ),
    .CASE35( 6'h23 ),
    .din35_WIDTH( 1 ),
    .CASE36( 6'h24 ),
    .din36_WIDTH( 1 ),
    .CASE37( 6'h25 ),
    .din37_WIDTH( 1 ),
    .CASE38( 6'h26 ),
    .din38_WIDTH( 1 ),
    .CASE39( 6'h27 ),
    .din39_WIDTH( 1 ),
    .CASE40( 6'h28 ),
    .din40_WIDTH( 1 ),
    .CASE41( 6'h29 ),
    .din41_WIDTH( 1 ),
    .CASE42( 6'h2A ),
    .din42_WIDTH( 1 ),
    .CASE43( 6'h2B ),
    .din43_WIDTH( 1 ),
    .CASE44( 6'h2C ),
    .din44_WIDTH( 1 ),
    .CASE45( 6'h2D ),
    .din45_WIDTH( 1 ),
    .CASE46( 6'h2E ),
    .din46_WIDTH( 1 ),
    .CASE47( 6'h2F ),
    .din47_WIDTH( 1 ),
    .CASE48( 6'h30 ),
    .din48_WIDTH( 1 ),
    .CASE49( 6'h31 ),
    .din49_WIDTH( 1 ),
    .CASE50( 6'h32 ),
    .din50_WIDTH( 1 ),
    .CASE51( 6'h33 ),
    .din51_WIDTH( 1 ),
    .CASE52( 6'h34 ),
    .din52_WIDTH( 1 ),
    .CASE53( 6'h35 ),
    .din53_WIDTH( 1 ),
    .CASE54( 6'h36 ),
    .din54_WIDTH( 1 ),
    .CASE55( 6'h37 ),
    .din55_WIDTH( 1 ),
    .CASE56( 6'h38 ),
    .din56_WIDTH( 1 ),
    .CASE57( 6'h39 ),
    .din57_WIDTH( 1 ),
    .CASE58( 6'h3A ),
    .din58_WIDTH( 1 ),
    .CASE59( 6'h3B ),
    .din59_WIDTH( 1 ),
    .CASE60( 6'h3C ),
    .din60_WIDTH( 1 ),
    .CASE61( 6'h3D ),
    .din61_WIDTH( 1 ),
    .CASE62( 6'h3E ),
    .din62_WIDTH( 1 ),
    .CASE63( 6'h3F ),
    .din63_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 1 ))
sparsemux_129_6_1_1_1_U147(
    .din0(survivor_q0),
    .din1(survivor_1_q0),
    .din2(survivor_2_q0),
    .din3(survivor_3_q0),
    .din4(survivor_4_q0),
    .din5(survivor_5_q0),
    .din6(survivor_6_q0),
    .din7(survivor_7_q0),
    .din8(survivor_8_q0),
    .din9(survivor_9_q0),
    .din10(survivor_10_q0),
    .din11(survivor_11_q0),
    .din12(survivor_12_q0),
    .din13(survivor_13_q0),
    .din14(survivor_14_q0),
    .din15(survivor_15_q0),
    .din16(survivor_16_q0),
    .din17(survivor_17_q0),
    .din18(survivor_18_q0),
    .din19(survivor_19_q0),
    .din20(survivor_20_q0),
    .din21(survivor_21_q0),
    .din22(survivor_22_q0),
    .din23(survivor_23_q0),
    .din24(survivor_24_q0),
    .din25(survivor_25_q0),
    .din26(survivor_26_q0),
    .din27(survivor_27_q0),
    .din28(survivor_28_q0),
    .din29(survivor_29_q0),
    .din30(survivor_30_q0),
    .din31(survivor_31_q0),
    .din32(survivor_32_q0),
    .din33(survivor_33_q0),
    .din34(survivor_34_q0),
    .din35(survivor_35_q0),
    .din36(survivor_36_q0),
    .din37(survivor_37_q0),
    .din38(survivor_38_q0),
    .din39(survivor_39_q0),
    .din40(survivor_40_q0),
    .din41(survivor_41_q0),
    .din42(survivor_42_q0),
    .din43(survivor_43_q0),
    .din44(survivor_44_q0),
    .din45(survivor_45_q0),
    .din46(survivor_46_q0),
    .din47(survivor_47_q0),
    .din48(survivor_48_q0),
    .din49(survivor_49_q0),
    .din50(survivor_50_q0),
    .din51(survivor_51_q0),
    .din52(survivor_52_q0),
    .din53(survivor_53_q0),
    .din54(survivor_54_q0),
    .din55(survivor_55_q0),
    .din56(survivor_56_q0),
    .din57(survivor_57_q0),
    .din58(survivor_58_q0),
    .din59(survivor_59_q0),
    .din60(survivor_60_q0),
    .din61(survivor_61_q0),
    .din62(survivor_62_q0),
    .din63(survivor_63_q0),
    .def(surv_fu_1616_p129),
    .sel(cur_state_fu_362),
    .dout(surv_fu_1616_p131)
);

viterbi_decoder_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            cur_state_fu_362 <= best_state_32;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            cur_state_fu_362 <= cur_state_1_fu_1884_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_fu_1397_p3 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_1_fu_366 <= add_ln302_fu_1511_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            t_1_fu_366 <= 5'd15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_11_fu_374 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_12_fu_378 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_13_fu_382 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_14_fu_386 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_15_fu_390 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_16_fu_394 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_17_fu_398 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_18_fu_402 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd9) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_19_fu_406 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd10) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_20_fu_410 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd11) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_21_fu_414 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd12) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_22_fu_418 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd13) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_23_fu_422 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd14) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_24_fu_426 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd15) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_25_fu_430 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln302_reg_2075 == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_fu_370 <= cur_state_fu_362[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln302_reg_2075 <= trunc_ln302_fu_1473_p1;
    end
end

always @ (*) begin
    if (((tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t = 5'd15;
    end else begin
        ap_sig_allocacmp_t = t_1_fu_366;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out10_ap_vld = 1'b1;
    end else begin
        p_out10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out11_ap_vld = 1'b1;
    end else begin
        p_out11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out12_ap_vld = 1'b1;
    end else begin
        p_out12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out13_ap_vld = 1'b1;
    end else begin
        p_out13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out14_ap_vld = 1'b1;
    end else begin
        p_out14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out15_ap_vld = 1'b1;
    end else begin
        p_out15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out4_ap_vld = 1'b1;
    end else begin
        p_out4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out5_ap_vld = 1'b1;
    end else begin
        p_out5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out6_ap_vld = 1'b1;
    end else begin
        p_out6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out7_ap_vld = 1'b1;
    end else begin
        p_out7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out8_ap_vld = 1'b1;
    end else begin
        p_out8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out9_ap_vld = 1'b1;
    end else begin
        p_out9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_1397_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_10_ce0_local = 1'b1;
    end else begin
        survivor_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_11_ce0_local = 1'b1;
    end else begin
        survivor_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_12_ce0_local = 1'b1;
    end else begin
        survivor_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_13_ce0_local = 1'b1;
    end else begin
        survivor_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_14_ce0_local = 1'b1;
    end else begin
        survivor_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_15_ce0_local = 1'b1;
    end else begin
        survivor_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_16_ce0_local = 1'b1;
    end else begin
        survivor_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_17_ce0_local = 1'b1;
    end else begin
        survivor_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_18_ce0_local = 1'b1;
    end else begin
        survivor_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_19_ce0_local = 1'b1;
    end else begin
        survivor_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_1_ce0_local = 1'b1;
    end else begin
        survivor_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_20_ce0_local = 1'b1;
    end else begin
        survivor_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_21_ce0_local = 1'b1;
    end else begin
        survivor_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_22_ce0_local = 1'b1;
    end else begin
        survivor_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_23_ce0_local = 1'b1;
    end else begin
        survivor_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_24_ce0_local = 1'b1;
    end else begin
        survivor_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_25_ce0_local = 1'b1;
    end else begin
        survivor_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_26_ce0_local = 1'b1;
    end else begin
        survivor_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_27_ce0_local = 1'b1;
    end else begin
        survivor_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_28_ce0_local = 1'b1;
    end else begin
        survivor_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_29_ce0_local = 1'b1;
    end else begin
        survivor_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_2_ce0_local = 1'b1;
    end else begin
        survivor_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_30_ce0_local = 1'b1;
    end else begin
        survivor_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_31_ce0_local = 1'b1;
    end else begin
        survivor_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_32_ce0_local = 1'b1;
    end else begin
        survivor_32_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_33_ce0_local = 1'b1;
    end else begin
        survivor_33_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_34_ce0_local = 1'b1;
    end else begin
        survivor_34_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_35_ce0_local = 1'b1;
    end else begin
        survivor_35_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_36_ce0_local = 1'b1;
    end else begin
        survivor_36_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_37_ce0_local = 1'b1;
    end else begin
        survivor_37_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_38_ce0_local = 1'b1;
    end else begin
        survivor_38_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_39_ce0_local = 1'b1;
    end else begin
        survivor_39_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_3_ce0_local = 1'b1;
    end else begin
        survivor_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_40_ce0_local = 1'b1;
    end else begin
        survivor_40_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_41_ce0_local = 1'b1;
    end else begin
        survivor_41_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_42_ce0_local = 1'b1;
    end else begin
        survivor_42_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_43_ce0_local = 1'b1;
    end else begin
        survivor_43_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_44_ce0_local = 1'b1;
    end else begin
        survivor_44_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_45_ce0_local = 1'b1;
    end else begin
        survivor_45_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_46_ce0_local = 1'b1;
    end else begin
        survivor_46_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_47_ce0_local = 1'b1;
    end else begin
        survivor_47_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_48_ce0_local = 1'b1;
    end else begin
        survivor_48_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_49_ce0_local = 1'b1;
    end else begin
        survivor_49_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_4_ce0_local = 1'b1;
    end else begin
        survivor_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_50_ce0_local = 1'b1;
    end else begin
        survivor_50_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_51_ce0_local = 1'b1;
    end else begin
        survivor_51_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_52_ce0_local = 1'b1;
    end else begin
        survivor_52_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_53_ce0_local = 1'b1;
    end else begin
        survivor_53_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_54_ce0_local = 1'b1;
    end else begin
        survivor_54_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_55_ce0_local = 1'b1;
    end else begin
        survivor_55_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_56_ce0_local = 1'b1;
    end else begin
        survivor_56_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_57_ce0_local = 1'b1;
    end else begin
        survivor_57_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_58_ce0_local = 1'b1;
    end else begin
        survivor_58_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_59_ce0_local = 1'b1;
    end else begin
        survivor_59_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_5_ce0_local = 1'b1;
    end else begin
        survivor_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_60_ce0_local = 1'b1;
    end else begin
        survivor_60_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_61_ce0_local = 1'b1;
    end else begin
        survivor_61_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_62_ce0_local = 1'b1;
    end else begin
        survivor_62_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_63_ce0_local = 1'b1;
    end else begin
        survivor_63_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_6_ce0_local = 1'b1;
    end else begin
        survivor_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_7_ce0_local = 1'b1;
    end else begin
        survivor_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_8_ce0_local = 1'b1;
    end else begin
        survivor_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_9_ce0_local = 1'b1;
    end else begin
        survivor_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        survivor_ce0_local = 1'b1;
    end else begin
        survivor_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln302_fu_1511_p2 = ($signed(ap_sig_allocacmp_t) + $signed(5'd31));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign cur_lo5_fu_1880_p1 = cur_state_fu_362[4:0];

assign cur_state_1_fu_1884_p3 = {{cur_lo5_fu_1880_p1}, {surv_fu_1616_p131}};

assign p_out = empty_25_fu_430;

assign p_out1 = empty_24_fu_426;

assign p_out10 = empty_15_fu_390;

assign p_out11 = empty_14_fu_386;

assign p_out12 = empty_13_fu_382;

assign p_out13 = empty_12_fu_378;

assign p_out14 = empty_11_fu_374;

assign p_out15 = empty_fu_370;

assign p_out2 = empty_23_fu_422;

assign p_out3 = empty_22_fu_418;

assign p_out4 = empty_21_fu_414;

assign p_out5 = empty_20_fu_410;

assign p_out6 = empty_19_fu_406;

assign p_out7 = empty_18_fu_402;

assign p_out8 = empty_17_fu_398;

assign p_out9 = empty_16_fu_394;

assign surv_fu_1616_p129 = 'bx;

assign survivor_10_address0 = zext_ln302_fu_1405_p1;

assign survivor_10_ce0 = survivor_10_ce0_local;

assign survivor_11_address0 = zext_ln302_fu_1405_p1;

assign survivor_11_ce0 = survivor_11_ce0_local;

assign survivor_12_address0 = zext_ln302_fu_1405_p1;

assign survivor_12_ce0 = survivor_12_ce0_local;

assign survivor_13_address0 = zext_ln302_fu_1405_p1;

assign survivor_13_ce0 = survivor_13_ce0_local;

assign survivor_14_address0 = zext_ln302_fu_1405_p1;

assign survivor_14_ce0 = survivor_14_ce0_local;

assign survivor_15_address0 = zext_ln302_fu_1405_p1;

assign survivor_15_ce0 = survivor_15_ce0_local;

assign survivor_16_address0 = zext_ln302_fu_1405_p1;

assign survivor_16_ce0 = survivor_16_ce0_local;

assign survivor_17_address0 = zext_ln302_fu_1405_p1;

assign survivor_17_ce0 = survivor_17_ce0_local;

assign survivor_18_address0 = zext_ln302_fu_1405_p1;

assign survivor_18_ce0 = survivor_18_ce0_local;

assign survivor_19_address0 = zext_ln302_fu_1405_p1;

assign survivor_19_ce0 = survivor_19_ce0_local;

assign survivor_1_address0 = zext_ln302_fu_1405_p1;

assign survivor_1_ce0 = survivor_1_ce0_local;

assign survivor_20_address0 = zext_ln302_fu_1405_p1;

assign survivor_20_ce0 = survivor_20_ce0_local;

assign survivor_21_address0 = zext_ln302_fu_1405_p1;

assign survivor_21_ce0 = survivor_21_ce0_local;

assign survivor_22_address0 = zext_ln302_fu_1405_p1;

assign survivor_22_ce0 = survivor_22_ce0_local;

assign survivor_23_address0 = zext_ln302_fu_1405_p1;

assign survivor_23_ce0 = survivor_23_ce0_local;

assign survivor_24_address0 = zext_ln302_fu_1405_p1;

assign survivor_24_ce0 = survivor_24_ce0_local;

assign survivor_25_address0 = zext_ln302_fu_1405_p1;

assign survivor_25_ce0 = survivor_25_ce0_local;

assign survivor_26_address0 = zext_ln302_fu_1405_p1;

assign survivor_26_ce0 = survivor_26_ce0_local;

assign survivor_27_address0 = zext_ln302_fu_1405_p1;

assign survivor_27_ce0 = survivor_27_ce0_local;

assign survivor_28_address0 = zext_ln302_fu_1405_p1;

assign survivor_28_ce0 = survivor_28_ce0_local;

assign survivor_29_address0 = zext_ln302_fu_1405_p1;

assign survivor_29_ce0 = survivor_29_ce0_local;

assign survivor_2_address0 = zext_ln302_fu_1405_p1;

assign survivor_2_ce0 = survivor_2_ce0_local;

assign survivor_30_address0 = zext_ln302_fu_1405_p1;

assign survivor_30_ce0 = survivor_30_ce0_local;

assign survivor_31_address0 = zext_ln302_fu_1405_p1;

assign survivor_31_ce0 = survivor_31_ce0_local;

assign survivor_32_address0 = zext_ln302_fu_1405_p1;

assign survivor_32_ce0 = survivor_32_ce0_local;

assign survivor_33_address0 = zext_ln302_fu_1405_p1;

assign survivor_33_ce0 = survivor_33_ce0_local;

assign survivor_34_address0 = zext_ln302_fu_1405_p1;

assign survivor_34_ce0 = survivor_34_ce0_local;

assign survivor_35_address0 = zext_ln302_fu_1405_p1;

assign survivor_35_ce0 = survivor_35_ce0_local;

assign survivor_36_address0 = zext_ln302_fu_1405_p1;

assign survivor_36_ce0 = survivor_36_ce0_local;

assign survivor_37_address0 = zext_ln302_fu_1405_p1;

assign survivor_37_ce0 = survivor_37_ce0_local;

assign survivor_38_address0 = zext_ln302_fu_1405_p1;

assign survivor_38_ce0 = survivor_38_ce0_local;

assign survivor_39_address0 = zext_ln302_fu_1405_p1;

assign survivor_39_ce0 = survivor_39_ce0_local;

assign survivor_3_address0 = zext_ln302_fu_1405_p1;

assign survivor_3_ce0 = survivor_3_ce0_local;

assign survivor_40_address0 = zext_ln302_fu_1405_p1;

assign survivor_40_ce0 = survivor_40_ce0_local;

assign survivor_41_address0 = zext_ln302_fu_1405_p1;

assign survivor_41_ce0 = survivor_41_ce0_local;

assign survivor_42_address0 = zext_ln302_fu_1405_p1;

assign survivor_42_ce0 = survivor_42_ce0_local;

assign survivor_43_address0 = zext_ln302_fu_1405_p1;

assign survivor_43_ce0 = survivor_43_ce0_local;

assign survivor_44_address0 = zext_ln302_fu_1405_p1;

assign survivor_44_ce0 = survivor_44_ce0_local;

assign survivor_45_address0 = zext_ln302_fu_1405_p1;

assign survivor_45_ce0 = survivor_45_ce0_local;

assign survivor_46_address0 = zext_ln302_fu_1405_p1;

assign survivor_46_ce0 = survivor_46_ce0_local;

assign survivor_47_address0 = zext_ln302_fu_1405_p1;

assign survivor_47_ce0 = survivor_47_ce0_local;

assign survivor_48_address0 = zext_ln302_fu_1405_p1;

assign survivor_48_ce0 = survivor_48_ce0_local;

assign survivor_49_address0 = zext_ln302_fu_1405_p1;

assign survivor_49_ce0 = survivor_49_ce0_local;

assign survivor_4_address0 = zext_ln302_fu_1405_p1;

assign survivor_4_ce0 = survivor_4_ce0_local;

assign survivor_50_address0 = zext_ln302_fu_1405_p1;

assign survivor_50_ce0 = survivor_50_ce0_local;

assign survivor_51_address0 = zext_ln302_fu_1405_p1;

assign survivor_51_ce0 = survivor_51_ce0_local;

assign survivor_52_address0 = zext_ln302_fu_1405_p1;

assign survivor_52_ce0 = survivor_52_ce0_local;

assign survivor_53_address0 = zext_ln302_fu_1405_p1;

assign survivor_53_ce0 = survivor_53_ce0_local;

assign survivor_54_address0 = zext_ln302_fu_1405_p1;

assign survivor_54_ce0 = survivor_54_ce0_local;

assign survivor_55_address0 = zext_ln302_fu_1405_p1;

assign survivor_55_ce0 = survivor_55_ce0_local;

assign survivor_56_address0 = zext_ln302_fu_1405_p1;

assign survivor_56_ce0 = survivor_56_ce0_local;

assign survivor_57_address0 = zext_ln302_fu_1405_p1;

assign survivor_57_ce0 = survivor_57_ce0_local;

assign survivor_58_address0 = zext_ln302_fu_1405_p1;

assign survivor_58_ce0 = survivor_58_ce0_local;

assign survivor_59_address0 = zext_ln302_fu_1405_p1;

assign survivor_59_ce0 = survivor_59_ce0_local;

assign survivor_5_address0 = zext_ln302_fu_1405_p1;

assign survivor_5_ce0 = survivor_5_ce0_local;

assign survivor_60_address0 = zext_ln302_fu_1405_p1;

assign survivor_60_ce0 = survivor_60_ce0_local;

assign survivor_61_address0 = zext_ln302_fu_1405_p1;

assign survivor_61_ce0 = survivor_61_ce0_local;

assign survivor_62_address0 = zext_ln302_fu_1405_p1;

assign survivor_62_ce0 = survivor_62_ce0_local;

assign survivor_63_address0 = zext_ln302_fu_1405_p1;

assign survivor_63_ce0 = survivor_63_ce0_local;

assign survivor_6_address0 = zext_ln302_fu_1405_p1;

assign survivor_6_ce0 = survivor_6_ce0_local;

assign survivor_7_address0 = zext_ln302_fu_1405_p1;

assign survivor_7_ce0 = survivor_7_ce0_local;

assign survivor_8_address0 = zext_ln302_fu_1405_p1;

assign survivor_8_ce0 = survivor_8_ce0_local;

assign survivor_9_address0 = zext_ln302_fu_1405_p1;

assign survivor_9_ce0 = survivor_9_ce0_local;

assign survivor_address0 = zext_ln302_fu_1405_p1;

assign survivor_ce0 = survivor_ce0_local;

assign tmp_fu_1397_p3 = ap_sig_allocacmp_t[32'd4];

assign trunc_ln302_fu_1473_p1 = ap_sig_allocacmp_t[3:0];

assign zext_ln302_fu_1405_p1 = ap_sig_allocacmp_t;

endmodule //viterbi_decoder_viterbi_decoder_Pipeline_TRACEBACK
