-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity convEncoder_Seq_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    state_load : IN STD_LOGIC_VECTOR (5 downto 0);
    in_word_data : IN STD_LOGIC_VECTOR (31 downto 0);
    p_out : OUT STD_LOGIC_VECTOR (5 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    encoded_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    encoded_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of convEncoder_Seq_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln40_fu_114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal encoded_fu_58 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal encoded_1_fu_247_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_62 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal i_2_fu_120_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_fu_66 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal or_ln_fu_225_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal bit_fu_136_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal bit_fu_136_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_163_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln10_fu_143_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_147_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_155_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln10_fu_171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln10_2_fu_183_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln10_1_fu_177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_195_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln11_1_fu_209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln11_fu_203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln13_fu_221_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal g2_fu_215_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal g1_fu_189_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal encoded_1_fu_247_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal encoded_1_fu_247_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal bit_fu_136_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal encoded_1_fu_247_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component convEncoder_Seq_bitselect_1ns_32ns_5ns_1_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component convEncoder_Seq_partset_64ns_64ns_2ns_6ns_64_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        DATA1WIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (63 downto 0);
        value : IN STD_LOGIC_VECTOR (1 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component convEncoder_Seq_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    bitselect_1ns_32ns_5ns_1_1_1_U1 : component convEncoder_Seq_bitselect_1ns_32ns_5ns_1_1_1
    generic map (
        DATAWIDTH => 32,
        ADDRWIDTH => 5)
    port map (
        din => in_word_data,
        sel => bit_fu_136_p2,
        dout => bit_fu_136_p3);

    partset_64ns_64ns_2ns_6ns_64_1_1_U2 : component convEncoder_Seq_partset_64ns_64ns_2ns_6ns_64_1_1
    generic map (
        DATAWIDTH => 64,
        DATA1WIDTH => 2,
        ADDRWIDTH => 6)
    port map (
        din => encoded_fu_58,
        value => encoded_1_fu_247_p2,
        sel => encoded_1_fu_247_p3,
        dout => encoded_1_fu_247_p4);

    flow_control_loop_pipe_sequential_init_U : component convEncoder_Seq_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    empty_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_fu_66 <= state_load;
                elsif (((icmp_ln40_fu_114_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_fu_66 <= or_ln_fu_225_p3;
                end if;
            end if; 
        end if;
    end process;

    encoded_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    encoded_fu_58 <= ap_const_lv64_0;
                elsif (((icmp_ln40_fu_114_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    encoded_fu_58 <= encoded_1_fu_247_p4;
                end if;
            end if; 
        end if;
    end process;

    i_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_62 <= ap_const_lv6_0;
                elsif (((icmp_ln40_fu_114_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_fu_62 <= i_2_fu_120_p2;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln40_fu_114_p2)
    begin
        if (((icmp_ln40_fu_114_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    bit_fu_136_p2 <= i_fu_62(5 - 1 downto 0);
    encoded_1_fu_247_p2 <= (g2_fu_215_p2 & g1_fu_189_p2);
    encoded_1_fu_247_p3 <= std_logic_vector(shift_left(unsigned(i_fu_62),to_integer(unsigned('0' & ap_const_lv6_1(6-1 downto 0)))));
    encoded_out <= encoded_fu_58;

    encoded_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln40_fu_114_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln40_fu_114_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            encoded_out_ap_vld <= ap_const_logic_1;
        else 
            encoded_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    g1_fu_189_p2 <= (xor_ln10_2_fu_183_p2 xor xor_ln10_1_fu_177_p2);
    g2_fu_215_p2 <= (xor_ln11_fu_203_p2 xor xor_ln11_1_fu_209_p2);
    i_2_fu_120_p2 <= std_logic_vector(unsigned(i_fu_62) + unsigned(ap_const_lv6_1));
    icmp_ln40_fu_114_p2 <= "1" when (i_fu_62 = ap_const_lv6_20) else "0";
    or_ln_fu_225_p3 <= (trunc_ln13_fu_221_p1 & bit_fu_136_p3);
    p_out <= empty_fu_66;

    p_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln40_fu_114_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln40_fu_114_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_155_p3 <= empty_fu_66(2 downto 2);
    tmp_2_fu_163_p3 <= empty_fu_66(5 downto 5);
    tmp_3_fu_195_p3 <= empty_fu_66(4 downto 4);
    tmp_fu_147_p3 <= empty_fu_66(1 downto 1);
    trunc_ln10_fu_143_p1 <= empty_fu_66(1 - 1 downto 0);
    trunc_ln13_fu_221_p1 <= empty_fu_66(5 - 1 downto 0);
    xor_ln10_1_fu_177_p2 <= (trunc_ln10_fu_143_p1 xor tmp_fu_147_p3);
    xor_ln10_2_fu_183_p2 <= (xor_ln10_fu_171_p2 xor tmp_1_fu_155_p3);
    xor_ln10_fu_171_p2 <= (tmp_2_fu_163_p3 xor bit_fu_136_p3);
    xor_ln11_1_fu_209_p2 <= (xor_ln10_fu_171_p2 xor tmp_3_fu_195_p3);
    xor_ln11_fu_203_p2 <= (tmp_fu_147_p3 xor tmp_1_fu_155_p3);
end behav;
