-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity convEncoder_Seq is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    s_axis_TVALID : IN STD_LOGIC;
    s_axis_TREADY : OUT STD_LOGIC;
    s_axis_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axis_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_TVALID : OUT STD_LOGIC;
    m_axis_TREADY : IN STD_LOGIC;
    m_axis_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of convEncoder_Seq is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "convEncoder_Seq_convEncoder_Seq,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.018000,HLS_SYN_LAT=19,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=156,HLS_SYN_LUT=247,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal state : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal s_axis_TDATA_blk_n : STD_LOGIC;
    signal tmp_nbreadreq_fu_70_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_reg_174 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_word_data_reg_178 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_word_last_reg_183 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s_reg_191 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start : STD_LOGIC;
    signal grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_done : STD_LOGIC;
    signal grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_idle : STD_LOGIC;
    signal grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_ready : STD_LOGIC;
    signal grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_p_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_p_out_ap_vld : STD_LOGIC;
    signal grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_encoded_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_encoded_out_ap_vld : STD_LOGIC;
    signal grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call4 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state4 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal trunc_ln48_fu_140_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component convEncoder_Seq_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        state_load : IN STD_LOGIC_VECTOR (5 downto 0);
        in_word_data : IN STD_LOGIC_VECTOR (31 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        encoded_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        encoded_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115 : component convEncoder_Seq_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start,
        ap_done => grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_done,
        ap_idle => grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_idle,
        ap_ready => grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_ready,
        state_load => state,
        in_word_data => in_word_data_reg_178,
        p_out => grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_p_out,
        p_out_ap_vld => grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_p_out_ap_vld,
        encoded_out => grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_encoded_out,
        encoded_out_ap_vld => grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_encoded_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call4) and (tmp_nbreadreq_fu_70_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_ready = ap_const_logic_1)) then 
                    grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                in_word_data_reg_178 <= s_axis_TDATA;
                in_word_last_reg_183 <= s_axis_TLAST;
                tmp_reg_174 <= tmp_nbreadreq_fu_70_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                p_s_reg_191 <= grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_encoded_out(63 downto 32);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state4) and (tmp_reg_174 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                state <= grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_p_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, m_axis_TREADY, tmp_nbreadreq_fu_70_p6, ap_CS_fsm_state3, ap_CS_fsm_state4, grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_done, ap_CS_fsm_state2, ap_block_state4, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (tmp_nbreadreq_fu_70_p6 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                elsif (((ap_const_boolean_0 = ap_block_state1) and (tmp_nbreadreq_fu_70_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((m_axis_TREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_done)
    begin
        if ((grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(m_axis_TREADY)
    begin
        if ((m_axis_TREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4)
    begin
        if ((ap_const_boolean_1 = ap_block_state4)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, s_axis_TVALID, tmp_nbreadreq_fu_70_p6)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_70_p6 = ap_const_lv1_1) and (s_axis_TVALID = ap_const_logic_0)));
    end process;


    ap_block_state1_ignore_call4_assign_proc : process(ap_start, s_axis_TVALID, tmp_nbreadreq_fu_70_p6)
    begin
                ap_block_state1_ignore_call4 <= ((ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_70_p6 = ap_const_lv1_1) and (s_axis_TVALID = ap_const_logic_0)));
    end process;


    ap_block_state4_assign_proc : process(m_axis_TREADY, tmp_reg_174)
    begin
                ap_block_state4 <= ((tmp_reg_174 = ap_const_lv1_1) and (m_axis_TREADY = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state4, ap_block_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, ap_block_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_state4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start <= grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_ap_start_reg;

    m_axis_TDATA_assign_proc : process(m_axis_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state4, tmp_reg_174, p_s_reg_191, ap_block_state4, trunc_ln48_fu_140_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_state4) and (tmp_reg_174 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axis_TDATA <= p_s_reg_191;
        elsif (((m_axis_TREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axis_TDATA <= trunc_ln48_fu_140_p1;
        else 
            m_axis_TDATA <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axis_TDATA_blk_n_assign_proc : process(m_axis_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state4, tmp_reg_174)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((tmp_reg_174 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            m_axis_TDATA_blk_n <= m_axis_TREADY;
        else 
            m_axis_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    m_axis_TKEEP <= ap_const_lv4_F;

    m_axis_TLAST_assign_proc : process(m_axis_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state4, tmp_reg_174, in_word_last_reg_183, ap_block_state4)
    begin
        if (((ap_const_boolean_0 = ap_block_state4) and (tmp_reg_174 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axis_TLAST <= in_word_last_reg_183;
        elsif (((m_axis_TREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axis_TLAST <= ap_const_lv1_0;
        else 
            m_axis_TLAST <= "X";
        end if; 
    end process;

    m_axis_TSTRB <= ap_const_lv4_F;

    m_axis_TVALID_assign_proc : process(m_axis_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state4, tmp_reg_174, ap_block_state4)
    begin
        if ((((ap_const_boolean_0 = ap_block_state4) and (tmp_reg_174 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((m_axis_TREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            m_axis_TVALID <= ap_const_logic_1;
        else 
            m_axis_TVALID <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_state1, s_axis_TVALID, tmp_nbreadreq_fu_70_p6)
    begin
        if (((tmp_nbreadreq_fu_70_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            s_axis_TDATA_blk_n <= s_axis_TVALID;
        else 
            s_axis_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_axis_TREADY_assign_proc : process(ap_CS_fsm_state1, tmp_nbreadreq_fu_70_p6, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (tmp_nbreadreq_fu_70_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_axis_TREADY <= ap_const_logic_1;
        else 
            s_axis_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    tmp_nbreadreq_fu_70_p6 <= (0=>(s_axis_TVALID), others=>'-');
    trunc_ln48_fu_140_p1 <= grp_convEncoder_Seq_Pipeline_VITIS_LOOP_40_1_fu_115_encoded_out(32 - 1 downto 0);
end behav;
